name: Convert .bib to .json

on: 
  push:
    paths:
      - 'content/publication_resources/bibtex/lahti.bib'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Read .bib and write .json
        uses: docker://pandoc/core:2.14.1
        with:
          args: >-
            --from=bibtex
            --to=csljson
            --output=data/publications/lahti.json
            content/publication_resources/bibtex/lahti.bib
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./data/publications/
          git commit data/publications/lahti.json -m 'bibtex2json update' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
