name: Convert .bib to .json

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Read .bib and write .json
        working-directory: ./content/publication_resources/bibtex
        uses: docker://pandoc/core:2.14.1
        with: 
          args: >-
            lahti_edit.bib 
            -t csljson
            lahti.json
