name: Convert .bib to .json

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Read .bib and write .json
        uses: docker://pandoc/core:2.14.1
        with:
          args: >-
            -t csljson
            --output=lahti.json
            lahti_edit.bib
      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
