name: Convert .bib to .json

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Read .bib and write .json
        uses: docker://pandoc/core:2.14.1
        with:
          args: >-
            --from=bibtex
            --to=csljson
            --output=output/lahti.json
            content/publication_resources/bibtex/lahti_edit.bib
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./output
          git commit output/lahti.json -m 'bibtex2json commit' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
